### ISSUE TITLE
Directory out of scope

### ISSUE THREAD

**Issue by transferplus** [innostudio/fileuploader#1]
I'm trying to upload a file with drag drop into a directory outside of this plugin structure.
The file is succefully loaded to 100% , no errors found, however if I look into the directory, there is nothing there.
So my question is: is the file being fisicaly uploaded right after being dragged or is this just happening after submitting the form?

The JSON response is [0] but it does show the file details under 'items'.
Thumbnail is also ok.

**Comment by innostudio** [comment]
@transferplus I would like to take a look with some screenshots or Teamviewer. If you think you can share me this, please write me an email on contact@innostudio.de.

Please also check before the php files if there the file input name is the same as in the html files.
