### ISSUE TITLE
delete doesn't work properly.

### ISSUE THREAD

**Issue by barrierwings-jay** [innostudio/fileuploader#11]
Env : Chrome 59

<a class="icon-jfi-trash jFiler-item-trash-action"></a>

I understood this one would delete file not only in HTML view but also file in filelist.

for example, you choose three files and delete one of them. When you submit your form, It should send two Files. But It sends three Files which you select in the first place.

I understood that <input type=files> has filelist type and It is kind of read-only and hard to manipulate. I was figuring out how to make delete function in my file list. I found this package. but It didn't work.

**Comment by abhishekejam** [comment]
Same issue here

**Comment by innostudio** [comment]
@barrierwings-jay @abhishekejam the Fileuploader is not able to remove or to add something to `<input type="file">`. Fileuploader is creating a `<input type="hidden">` element where you can find the current list of files.
