### ISSUE TITLE
how can i send multiples files at the same time on button click via ajax?

### ISSUE THREAD

**Issue by tdias25** [innostudio/fileuploader#12]
i'm using the basic implementation, with no autostart and with no ajax, just a regular form and a button, i want to know if its possible to send multiple files with ajax on button click.

**Comment by innostudio** [comment]
@tdias25 in this case you will need to submit the entire form. Using the basic jQuery.ajax request, you can send the form inputs to the back-end (ex: https://github.com/CreativeDream/jquery.uploader).

**Comment by tdias25** [comment]
that's not the same plugin isn't it? and i tried something like that but it came empty

**Comment by tdias25** [comment]
or its possible to desactive the "autostart" and then on button click trigger the event and show the progress bar
