### ISSUE TITLE
Is it possible to let the user add a caption

### ISSUE THREAD

**Issue by philouphil** [innostudio/fileuploader#15]
Hello,

I'm discovering your great work and I must say that I'm impressed !

I've just a special need to fill before suscribing the extended license.

I'm using that example https://innostudio.de/fileuploader/documentation/examples/sorter/upload/

In my project, the goal is to let the user create a photo gallery with captions very easily. 

So this is what I'd like to have, step by step:
1- the user uploads only images (jpg jpeg png gif bmp ...) : OK
2- the user can preview the images in thumbnails and sort them in a specific order : OK
3- the user can write for each thumbnail a short description/caption => I need a little input field on/under/over each thumbnail for that
4- Finally I need to submit the "data content" of the download area through a php formular.
I mean to submit, in the order sorted by the user, only the url of the images and their captions. Something like `$post='<img src="http://url/image1" title="caption1 wrote by user"/><img src="http://url/image2" title="caption2 wrote by user"/><img .... />';`

Do you have any idea of doing that ?

Really really by thanks for your work and for your help !

Philippe

**Comment by innostudio** [comment]
@philouphil yes it is possible. You will need to add the HTML input into the `thumbnails.item` option. The functionality should be done by your own.
