### ISSUE TITLE
Respect EXIF Orientation

### ISSUE THREAD

**Issue by meare** [innostudio/fileuploader#18]
It would be really nice if plugin could automatically rotate photos depending on EXIF data

![screen shot 2017-11-23 at 19 57 50](https://user-images.githubusercontent.com/3748248/33185057-bd4ed6bc-d088-11e7-951a-a775a9af9d83.png)

![screen shot 2017-11-23 at 19 58 10](https://user-images.githubusercontent.com/3748248/33185056-bd0e27b6-d088-11e7-8027-d6298eaba0f6.png)

**Comment by innostudio** [comment]
@meare Download the v1.4.
