### ISSUE TITLE
Safari - no change event is binded

### ISSUE THREAD

**Issue by s0By** [innostudio/fileuploader#2]
Don't really understand why the code was removed from git in the first day, but to start off with project issues. In safari uploader doesn't work at all, no animations, no upload, nothing. It did worked before while it was jquery filer, so something apparently changed since that time.

I assume general plugin issues will be always addressed and fixed or they go under '1 year professional support' as well? I'd consider buying at least 1 commercial license, since I was full time 'filer' user, but it has to work properly first and complete my needs.

**Comment by innostudio** [comment]
@s0By are you testing the Safari Browser on Mac or Windows?

**Comment by s0By** [comment]
@innostudio On mac

**Comment by innostudio** [comment]
@s0By Hmm. What kind of Safari version do you have?

**Comment by s0By** [comment]
@innostudio Version 9.1.2 (11601.7.7) and OS X is El Capitan 10.11.6, the plugin itself sort of works, It doesn't give any errors, it inits, but when you select a file it doesn't do any network requests and doesn't continue.
P.S.
Tested again, drag and drop seems to work, but selecting through browse doesn't.
<img width="1373" alt="screen shot 2017-03-27 at 12 54 04" src="https://cloud.githubusercontent.com/assets/6382468/24350866/8710f882-12ec-11e7-935f-764e07a27a7f.png">

**Comment by innostudio** [comment]
@s0By I tested it again and it seems to work also through "Browse Files". What about other examples?

**Comment by s0By** [comment]
@innostudio nope, none of those 3 on the main page seems to work, only with drag and drop. It seems that JS doesn't get that something was selected. 
For example, on the second example, with the form. When you select a file it still says "Choose files to upload", while (for example) in mozilla if I select 1 it will upload it and say "1 file was choosen".

But Submit Form button returns in php data of file (in all browsers), so something works, something doesn't. I'll take a look as well.

**Comment by s0By** [comment]
function `getAllEvents`, for some reason the input element doesn't give "on" events in safari, so you don't get "onclick", "onsubmit", etc, which results in empty result array and that is why there's no binding.

**Comment by innostudio** [comment]
@s0By can you contact me on contact@innostudio.de? I would like to test it too.

**Comment by innostudio** [comment]
Fixed in Version: 1.0.0.1 (27-Mar-2017)
