### ISSUE TITLE
Images once sent in AJAX not available on form submit

### ISSUE THREAD

**Issue by rathodbhavikkqc** [innostudio/fileuploader#27]
I am using an image uploading library innostudio/fileuploader, in which AJAX is necessary for Drag & Drop Feature, now i don't want to upload images on AJAX but for drag & drop i've made random empty function which creates nothing (not uploading an image). I want to upload image on form submit, but the issue is i'm getting $_FILES empty if i uses AJAX, i've tried sending uploaded image in base64 format which causing POST request error. (Request entity Too Large)

**Comment by innostudio** [comment]
Hello,

in this case I will recommend to use the following example: https://innostudio.de/fileuploader/documentation/examples/drag-drop-form/
