### ISSUE TITLE
Need to configure with Easy digital download for Frontend Submission form

### ISSUE THREAD

**Issue by JsarkarGit** [innostudio/fileuploader#28]
I'm Using [EDD](https://easydigitaldownloads.com/) [FES](https://easydigitaldownloads.com/downloads/frontend-submissions/) I need to configure the fileuploader in the vendor submission form but I can't do this. anywone can help me?

Here are some usefull link
https://docs.easydigitaldownloads.com/article/957-frontend-submissions-submission-form
https://docs.easydigitaldownloads.com/article/654-amazon-s3-and-frontend-submissions

**Comment by innostudio** [comment]
unfortunatelly no, sorry
