### ISSUE TITLE
Preloaded files

### ISSUE THREAD

**Issue by ionspicica** [innostudio/fileuploader#30]
Hello. When I use preloaded files everything works fine thumbnails is shown i can edit them delete etc, the problem is that when I try to post the form the files are missing from the parameters

**Comment by blackchineykh** [comment]
I'm having the same issue. @ionspicica  @innostudio  was there a solution for this?

**Comment by ionspicica** [comment]
Hi, unfortunately I didn’t found solution for this issue, but if files are
preloaded they might be already saved. If you make new POST request with
preloaded files then files are already saved and you can get them from db,
if you select new files then you can get them from the request

**Comment by innostudio** [comment]
@blackchineykh @ionspicica while preloading the files and submitting the form, you will get only the list with the file names in $_POST. This list should be merged with the preloaded files on the backend using the option `files` - [Documentation](https://innostudio.de/fileuploader/documentation/#php)

Checkout our example:
https://innostudio.de/fileuploader/documentation/examples/preloaded-files/

**Comment by ionspicica** [comment]
I use python, how do I get the files in this case

сб, 2 мар. 2019 г. в 13:40, Iulian Galciuc <notifications@github.com>:
