### ISSUE TITLE
Get data-attribute from file

### ISSUE THREAD

**Issue by tornako** [innostudio/fileuploader#32]
Hello, how can I get the value of a data-attribute from the input field of the image?

I imagine that with callback features. 

`onSelect: function(item) {
  var ep =  $(this).attr("data-ep");
        },`

Thanks!

**Comment by innostudio** [comment]
@tornako using the following code:

`onSelect: function(item, listEl, parentEl, newInputEl, inputEl) { var ep = inputEl.attr('data-ep'); },`

**Comment by tornako** [comment]
Thank you very much, it's going great!
