### ISSUE TITLE
Translate to different languages

### ISSUE THREAD

**Issue by tornako** [innostudio/fileuploader#34]
Where do I put the "Captions" code to have the translation in different languages?

Thank you so much

**Comment by innostudio** [comment]
@tornako like this:

```// 3. call fileuploader instance
$('input[name="files"]').fileuploader({
    captions: {}
});```

**Comment by tornako** [comment]
Thank you, but for a multilanguage? How I put different languages in the same captions? Ex. Catalan, Spanish and English.

Thanks!!
