### ISSUE TITLE
Caption in multiple languages

### ISSUE THREAD

**Issue by tornako** [innostudio/fileuploader#36]
Hi, is possible to have the caption for multilanguages? How I put different languages in the same captions? Ex. Catalan, Spanish and English.

(I write a new post because the other is already closed, and so it is visible.)

Thanks!!

**Comment by innostudio** [comment]
@tornako there is no way to have in the `captions` object different languages at the same time.

**Comment by innostudio** [comment]
The simplest way is following

**HTML:**
~~~html
<script type="text/javascript">
    window.appLanguage = 'en';
</script>
~~~

**Custom.js:**
~~~js
// declare translations
var fileuploaderTranslations = {
    en: {
        button: 'Browse files'
    },
    es: {
        button: 'Examinar...'
    }
};

// init fileuploader
$('input:file').fileuploader({
    captions: fileuploaderTranslations[window.appLanguage]
});
~~~

**Comment by innostudio** [comment]
@tornako the plugin is now translated in 14 languages. Check it here https://innostudio.de/fileuploader/documentation/#options-captions
