### ISSUE TITLE
Multiple instances

### ISSUE THREAD

**Issue by TardencillaRuiz** [innostudio/fileuploader#37]
Hi,

How can I use multiple instances on the same page?

Thanks.

**Comment by innostudio** [comment]
@Tardencilla like this:

~~~html
<input type="file" name="files1" id="files1">
<input type="file" name="files2" id="files2"`>
~~~

~~~js
$('#files1').fileuploader({});
$('#files2').fileuploader({});
~~~

**Comment by myrandor** [comment]
Is it possible to use Sorter() out of their input?

Ex: Move an image from "files1" to "files2".

**Comment by innostudio** [comment]
@myrandor currently no.

**Comment by bagbaq** [comment]
> @Tardencilla like this:
> 
> ```
> <input type="file" name="files1" id="files1">
> <input type="file" name="files2" id="files2"`>
> ```
> 
> ```js
> $('#files1').fileuploader({});
> $('#files2').fileuploader({});
> ```

That didn't work on me. I set the both of it's name attribute to **"files[]"** and magically it start working!
