### ISSUE TITLE
Validate extension

### ISSUE THREAD

**Issue by tornako** [innostudio/fileuploader#38]
Hi,

I want to validate the extensions with a function because I have several forms of files and images, and depending on what is used, I must allow one extension or another.

Can you give me an idea of ​​how to do it?

I imagine that with the following:

`
onFilesCheck: function(files, options, listEl, parentEl, newInputEl, inputEl) {
			
			if(inputEl.attr('data-apt') == 'logotip'){
				alert('form 1');
				disallowedExtensions: ['text/plain', 'audio/*']
			} else {
				alert('form 2');
				disallowedExtensions: ['jpg', 'jpeg', 'png']
			}
			
			return true;
		},
`

The alerts are working, but not the dissallowedExtensions.

Thanks!

**Comment by innostudio** [comment]
@tornako we would recommend you the following code:

~~~js
enableApi: true,
afterRender: function(listEl, parentEl, newInputEl, inputEl) {
    var api = $.fileuploader.getInstance(inputEl);

    if (inputEl.attr('data-apt') == 'logotip')
        api.getOptions().disallowedExtensions = ['text/plain', 'audio/*'];
     else
        api.getOptions().disallowedExtensions = ['jpg', 'jpeg', 'png'];
},
~~~

**Comment by tornako** [comment]
Thanks, it's working!

:)
