### ISSUE TITLE
Upload silently fails on large (>~10MB) image upload

### ISSUE THREAD

**Issue by 2MAX-io** [innostudio/fileuploader#39]
On Google Chrome, when uploading large file, around 10MB, for example:
https://upload.wikimedia.org/wikipedia/commons/f/ff/Pizigani_1367_Chart_10MB.jpg

using example: examples/image-editor/client-side/

or on home page of this plugin using example of image editor: https://i.imgur.com/Ibw5QZP.png

after adding file like this, file uploader seems to fail silently, it does not display miniature of image, and it does not upload image via XHR request, so it does not seem like any backend limit

it looks like that after upload:
https://i.imgur.com/Ibw5QZP.png

from my analysis it seems, when uploading large files, callback related to saving, reading from blob, onload of image do not fire

I do not know if it is some hard limit of browser, or some kind of bug but in any case there should be some error message for failed upload

also in example: examples/image-editor/client-side/
```
	$('input[name="files"]').fileuploader({
		limit: 20,
		fileMaxSize: 20,
```

`fileMaxSize: 20,`

suggest that upload of 20MB should be supported but it does not seems to be the case

either way there should be some kind of error in case of this error

also when this problem occurs, image being not successfully uploaded like that, is still put inside input `fileuploader-list-` as JSON, in my case `fileuploader-list-files`, that is used in backend, and this makes errors in case of failed uploads like this

**Comment by innostudio** [comment]
Hello,

Thank you that you notice this.

By default we have a `reader.maxSize: 9` for the FileReader. Just set it to your fileMaxSize please.

Check the `reader:` option here:
https://innostudio.de/fileuploader/documentation/#options-others
