### ISSUE TITLE
Maximum File Size

### ISSUE THREAD

**Issue by jayakaran** [innostudio/fileuploader#43]
Is there a theoretical file size limit for a file that is uploaded using this software?

**Comment by innostudio** [comment]
Sure
https://innostudio.de/fileuploader/documentation/#options-validations

**Comment by jayakaran** [comment]
I know what the specification says about setting the file. My question is more on a practical side. If I had a 10GB file would this plugin perform the same as it would with a 1GB file? If the 1GB file took a minute would 10 GB take 10 minutes?

**Comment by innostudio** [comment]
@jayakaran No. The plugin is no that thing that is controlling the performance of upload. This is the server and internet.

**Comment by innostudio** [comment]
@jayakaran By the way, don't forget to use `upload` option and it's `chunk` setting when uploading such a large file.

https://innostudio.de/fileuploader/documentation/#options-ajax
