### ISSUE TITLE
Safari Image Editor

### ISSUE THREAD

**Issue by danielvloggs** [innostudio/fileuploader#46]
Hello,

when I upload an image with the latest Safari and then open it automatically with the image editor, there is a problem with the editor. See image. Can you look at the problem?

[Image Editor Problem](https://ibb.co/6nf4ymY)

Thanks Daniel

**Comment by innostudio** [comment]
@danielvloggs thank you for reporting the issue. We are still looking for a solution and will write here as soon as we get it fixed.

**Comment by innostudio** [comment]
@danielvloggs Good news. Please download fileuploader again and update the file jquery.fileuploader.min.js. The bug should be fixed now.
