### ISSUE TITLE
IE11 not loading editor-view

### ISSUE THREAD

**Issue by ghost** [innostudio/fileuploader#49]
When using IE11 we cannot open the editor view. I can see the loading spinner (which is not spinning due to the lack of support of animated svg: won't solve) but then nothing happens and I can't exit the situation without reloading the page. There are no messages shown in the console. The network inspector shows successful loading of the image (when editing a preloaded file). But we see the same issue after uploading a new image (even on your demo-pages).

I guess some kind of event is not triggered on image load. Please could you have a look into this. We sadly still need to support IE11 and fileuploader is stated to support >IE10. 

All other Browsers we have tested are working just fine, including Edge, Chrome, Firefox and Safari.

Thanks in advance.

**Comment by innostudio** [comment]
@ahlvd thank you for reporting the issue.

The problem was that on IE wasn't triggered `onload` callback after cloning the node.

**The problem was fixed** now by forcing the callback. Please update the jquery.fileuploader.min.js.

**Comment by ghost** [comment]
@innostudio Wow, that was fast. 
Works now. Thanks!
