### ISSUE TITLE
need event 

### ISSUE THREAD

**Issue by mohamad68** [innostudio/fileuploader#5]
hi
is any event to trigger  when user add image and showing it's thumbnail ?

**Comment by CreativeDream** [comment]
@mohamad68 just take a loot at the http://innostudio.de/fileuploader/documentation/#documentation and you will find some.

I think that the options that you need is: `onItemShow `or `onImageLoaded`. Just take a look in the documentation and you will find the description about this callbacks.

**Comment by innostudio** [comment]
@mohamad68 just take a loot at the http://innostudio.de/fileuploader/documentation/#documentation and you will find some.

I think that the options that you need is: `onItemShow `or `onImageLoaded`. Just take a look in the documentation and you will find the description about this callbacks.
