### ISSUE TITLE
How to enter optional title for each file and send all (file + title pair) to server when submit?

### ISSUE THREAD

**Issue by mrhieuit** [innostudio/fileuploader#51]
![2020-02-20_21-28-47](https://user-images.githubusercontent.com/17003983/74947325-41a7d100-542d-11ea-9d11-cc67fd59a31b.jpg)

**Comment by innostudio** [comment]
@mrhieuit Hello.

1. Add the input in thumbnails option: `item` and `item2`
`<input type="text" name="optional_title">`
https://innostudio.de/fileuploader/documentation/#options-templates

2. Enable API using `enableApi: true`
https://innostudio.de/fileuploader/documentation/#api

3. Bind the text input to each file when submitting the form
~~~js
$('form').on('submit', function(e) {
    var $input = $(this).find('input:file'); // input selector
    var api = $.fileuploader.getInstance($input); // get api methods

    // bind
    for(var i = 0; i<api.getFiles().length; i++) {
        var item = api.getFiles()[i];

        // create listProps object if you don't have one
        if (!item.data.listProps)
            item.data.listProps = {};

        // add optional_title to the fileuploader's hidden input
        item.data.listProps.optional_title = item.html.find('input[name="optional_title"]').val();
    }
});
~~~

4. Get the optional_title using PHP
~~~php
$fileList = $FileUploader->getFileList();

$fileList[0]['listProps']['optional_title']; // this is your optional_title for first file
~~~

**Comment by mrhieuit** [comment]
Hello @innostudio, 
Thanks for your answer. I believe your answer was very detailed.

Could you please get the optional_title using ASP.NET webform?

**Comment by innostudio** [comment]
@mrhieuit in step 4 just replace the code with `fileUploader.GetFileList()`

**Comment by mrhieuit** [comment]
You helped me save time. Many thanks!
