### ISSUE TITLE
How to use multiple size in Gallery ajax.php

### ISSUE THREAD

**Issue by mzhossain** [innostudio/fileuploader#52]

**Comment by mzhossain** [comment]
`
![image](https://user-images.githubusercontent.com/9637958/77139767-7d23d280-6aa1-11ea-8fae-13751a047198.png)
`
This is the code i tried to copy and change variablenames. It works only if i disable one instance. How to run 2 instance for same input field?

**Comment by mzhossain** [comment]
Incase if the image os not showing...here is the code


```
$FileUploader = new FileUploader('files', array(
			'limit' => 1,
			'fileMaxSize' => 20,
			'extensions' => array('image/*', 'video/*', 'audio/*'),
			'uploadDir' => $realUploadDir,
			'required' => true,
			'title' => $title,
			'replace' => $id,
			'editor' => array(
				'maxWidth' => 800,
				'maxHeight' => 800,
				'crop' => false,
				'quality' => 90
			)
		));
        $upload = $FileUploader->upload();
```

**Comment by innostudio** [comment]
Using ::resize method
https://innostudio.de/fileuploader/documentation/#php
