### ISSUE TITLE
Avatar file route problem in Symfony 5

### ISSUE THREAD

**Issue by lukaszkulinski** [innostudio/fileuploader#55]
Hi, I can't generate thumbnail for uploaded avatar when route of page has more elements than one.

This is my data-fileuploader-files value: [{"file":"uploads/horse_profile_pictures/survey-5ef1bf5c254df.jpeg"}]

When the route is: localhost/avatar, then works fine

but when the route is: localhost/avatar/username,
then script try to find file in:

localhost/**avatar**/uploads/horse_profile_pictures 
instead of
localhost/uploads/horse_profile_pictures

**Comment by innostudio** [comment]
Hello, try to change the `file` attribute and put a public url and `local` attribute as information for backend. Here is an example:

~~~js
[{
    name: 'survey-5ef1bf5c254df.jpeg',
    size: 1024,
    type: 'image/jpeg',
    file: 'http://localhost/avatar/uploads/horse_profile_pictures/survey-5ef1bf5c254df.jpeg',
    local: 'uploads/horse_profile_pictures/survey-5ef1bf5c254df.jpeg' // this attribute will go in the hidden input
}]
~~~
