### ISSUE TITLE
The image uploaded is the original image, not the edited one.

### ISSUE THREAD

**Issue by lander16** [innostudio/fileuploader#58]
I'm using the uploader on a form, do I need to do something in the onSave callback of the editor in order for the form to upload the edited image? I'm getting the original one instead of the edited one.

Thanks

**Comment by innostudio** [comment]
@lander16 if you are not using our class on backend, the client-side example is required

https://innostudio.de/fileuploader/documentation/examples/image-editor/client-side/js/custom.js

**Comment by lander16** [comment]
Thanks for the prompt reply, I see that the client example uses ajax for the file upload, I want to do it on a form, but it seems that deleting/appending data to the form as it's done in the upload method of the example is not available outside of the beforeSend callback. Anyway to implement this without ajax?

**Comment by innostudio** [comment]
@lander16 unfortunately no. There is no way to manipulate input element using JavaScript.
