### ISSUE TITLE
What happend to old repository Issues, and why have a Github page if no code ? 

### ISSUE THREAD

**Issue by rehanvdm** [innostudio/fileuploader#6]
What happened to old repository Issues, and why have a Github page if no code ?

**Comment by innostudio** [comment]
@rehanvdm the old version is gone. Github page is for issues and changelogs.

I will post the code here in the future on the Github too.

**Comment by lenamtl** [comment]
Is there a way to get the old issues? 
Maybe from a backup, as there was a lot of useful information and some custom code that may help ..precious information.

Is there a lot of change form previous version or only the name changed?

Thanks

**Comment by innostudio** [comment]
@lenamtl there are many changes.

You can also find some examples here: https://innostudio.de/fileuploader/documentation/#examples

**Comment by lenamtl** [comment]
Ok and now it's required a license. You should put the license text on the project page.

Does the previous version will be maintained by someone ?

**Comment by innostudio** [comment]
@lenamtl maintained? currently not. If is too hard to update to the new version, maybe I could help you. Write me an E-mail and I will take a look at your problem.

**Comment by lenamtl** [comment]
Ok thanks
