### ISSUE TITLE
Some bugs then user use Drag & Drop 

### ISSUE THREAD

**Issue by Onore** [innostudio/fileuploader#65]
Hi.

I use the fileuploader with PHP Form Builder.

It is **only** if I put file using **Drag & Drop**.

Bugs
1. https://prnt.sc/uomodj
2. https://prnt.sc/unrnu4

I can receate it on https://innostudio.de/fileuploader/documentation/#examples
Because the examples does not have any restiction/validation :(

**Comment by innostudio** [comment]
@Onore Hi.

You are doing the validation in JavaScript or in PHP?
can you paste here also the configuration code?

**Comment by Onore** [comment]
I have used it as a component of PHPFormBuilder
