### ISSUE TITLE
Array provided to 'preload' is reversed in rendered output

### ISSUE THREAD

**Issue by wrabit** [innostudio/fileuploader#66]
My payload given to 'preload' is:

(renamed to my order column value for debugging)

``` lang-json
[
   {
      "name":"\"1\"",
      "size":46011,
      "size2":"44.93 KB",
      "type":"image\/jpeg",
      ...
   },
   {
      "name":"\"2\"",
      "size":62579,
      "size2":"61.11 KB",
      "type":"image\/jpeg",
      ...     
   },
   {
      "name":"\"3\"",
      "size":62579,
      "size2":"61.11 KB",
      "type":"image\/jpeg",
      ...   
   },
   {
      "name":"\"4\"",
      "size":55983,
      "size2":"54.67 KB",
      "type":"image\/jpeg",
      ...
   }      
]
```

And the default output is:

![image](https://user-images.githubusercontent.com/5918271/97853495-7710f800-1cf8-11eb-9188-0a793e119b85.png)

My preload code:

```
        // preload existing files
        @this.preload()
          .then(result => {
            console.log(result)
            var api = $.fileuploader.getInstance($fileuploader),
                preload = []
            try {
              // preload the files
              preload = JSON.parse(result)
              api.append(preload)
            } catch (e) {}
          });
```

Console.log outputs:

![image](https://user-images.githubusercontent.com/5918271/97853809-e850ab00-1cf8-11eb-8f7f-8dcad6ec8af8.png)

Is this behaviour by design?

**Comment by wrabit** [comment]
I can understand the lack of response on an opensource package, but I paid for this, also email sent to your company and no response. Warning to potentional buyers. Support level -2000

**Comment by innostudio** [comment]
@wrabit sorry for such a late answer. In custom.js you will find the option `itemPrepend`, set it false. Or you can reverse the array before preloading the files.

https://innostudio.de/fileuploader/documentation/#options-templates
