### ISSUE TITLE
beforeSend and remove at uploading stage

### ISSUE THREAD

**Issue by s0By** [innostudio/fileuploader#7]
```
// Callback fired before uploading a file
// by returning false, you can prevent the upload
beforeSend: function(item, listEl, parentEl, newInputEl, inputEl) {
	// example:
	// here you can extend the uploading data
	item.upload.data.new_data_attribute = 'nice';

	return true;
}
```
The example that is provided in documentation doesn't seem to work. It's not even assigning anything to data. If you'll do `item.upload.new_data_attribute = 'nice';` it will be there at uploading stage but won't be transferred to uploaded file. 
As a temporary workaround I'm currently assigning attributes in `onSuccess` stage which is not an ideal solution.

Also I have a problem with `onRemove`. When the file is already uploaded and I try to remove it - everything is ok. If I try to remove the file while it's still being uploaded I get `Illegal invocation` error and then the whole `onRemove` stops working, even on uploaded files. 

<img width="765" alt="screen shot 2017-05-23 at 10 44 23" src="https://cloud.githubusercontent.com/assets/6382468/26343718/c7ee8000-3fa5-11e7-9b1d-cf1744ec85d6.png">

**Comment by CreativeDream** [comment]
@s0By i've tested with https://innostudio.de/fileuploader/documentation/examples/default-upload/

What example are you using?
Try to use the unminified script and write the exact line of the error

**Comment by innostudio** [comment]
@s0By i've tested with https://innostudio.de/fileuploader/documentation/examples/default-upload/

What example are you using?
Try to use the unminified script and write the exact line of the error

**Comment by s0By** [comment]
For the `Illegal invocation` part, I think that was my issue. The problem was with ajax request that is being generated. It tried to pass some data, that didn't exist during upload stage, so I was getting undefined data. 

In my use case I'm renaming the file during upload so I don't know the new name of the file until upload is complete. So for my case I had to turn `onRemove` off until the file is uploaded, only then I'm able to successfully remove a file.

But `beforeSend` question remains open.

**Comment by innostudio** [comment]
@s0By I can take a look, but it's oddly that it works in all examples and not working for you. Write me an Email with your Teamviewer authentication details.

**Comment by innostudio** [comment]
No answer.
Closed.

**Comment by s0By** [comment]
Sorry. Forgot to write. Since I'm manipulating the file on the serverside and changing some properties of it there, `beforeSend` was pretty pointless for me, so even tho it didn't work for me (even if I needed it) I managed to do things with regular ajax request.

**Comment by Sam-Butler** [comment]
How did you get back the response from the AJAX request?
