### ISSUE TITLE
onFilesCheck asnychronous?

### ISSUE THREAD

**Issue by ghost** [innostudio/fileuploader#70]
I'm encountering the problem that I have to check the length (in seconds) of a video file before upload. Sadly this is an asynchronous task, thus waiting for a callback. As far as I understand, the onFilesCheck Callback only allows for returning a boolean value. Is there any build-in possibility to pass back a Promise or callback?

Example (does actually not work, because it does not return boolean):
```
onFilesCheck(files, options, listEl, parentEl, newInputEl, inputEl) {
        let promises = Array.from(files).map(file => {
            return new Promise((resolve, reject) => {
                const video = document.createElement('video');
                video.preload = "metadata";
                video.onloadedmetadata = function () {
                    URL.revokeObjectURL(video.src);
                    var duration = video.duration;
                    if (duration > 10) {
                        reject('too long');
                    } else {
                        resolve();
                    }
                }
                video.src = URL.createObjectURL(file);
            });
        });
        return Promise.all(promises);
    }
```

**Comment by onesideat** [comment]
@ahlvd in the current version it is not possible. The only way will be (if you are using ajax mode) to set `start: false` and in `onSelect` to do the check. If the duration is ok, just to call `item.upload.send();`

**Comment by ghost** [comment]
Nice workaround. Thanks.
