### ISSUE TITLE
How to show existing uploaded files?

### ISSUE THREAD

**Issue by shan141** [innostudio/fileuploader#8]
Hi, I want to show already uploaded files in drag-drop file upload, so that i can edit/update files. 
need guidance. I couldn't find way to show existing files in your documentation. 

Thanks.

**Comment by anonfidusa** [comment]
@shan141 I have the same problem toó, you have solved it? i use php

**Comment by shan141** [comment]
@anonfidusa  not yet . let me know if you find any way .

**Comment by innostudio** [comment]
@shan141 [Appended Files Example](https://innostudio.de/fileuploader/documentation/examples/appended-files/)

Show existing files by:
- Using `files` config
- Using `data-fileuploader-files` attribute
